# Generated by Django 5.0.4 on 2024-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencione',
            old_name='precio_insumos',
            new_name='Precio_Atencion',
        ),
        migrations.AddField(
            model_name='atencione',
            name='precio_consulta',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4),
        ),
    ]
