# Generated by Django 5.0.4 on 2024-05-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVete', '0003_remove_atencione_precio_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='vencimiento',
            field=models.DateField(default=None),
        ),
    ]
