# Generated by Django 5.0.4 on 2024-05-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVete', '0005_alter_proveedore_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='talle',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2),
        ),
    ]
