# Generated by Django 5.0.4 on 2024-05-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVete', '0006_articulo_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='talle',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='vencimiento',
            field=models.DateField(blank=True, default=None),
        ),
    ]
