# Generated by Django 5.0.4 on 2024-05-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVete', '0010_alter_articulo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
