# Generated by Django 5.0.4 on 2024-05-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVete', '0011_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencione',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
